name: Check File Sizes

on:
  push:
    branches:
      - main

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      run: |
        chmod +x check.sh
        OUTPUT=$(./check.sh)
        if [[ $OUTPUT =~ "Error: File" ]]; then
          echo "::error::${OUTPUT}"
          exit 1
        fi
        echo "All assets match required size"
