name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      # - synchronize
      # - reopened
    branches:
      - main
    paths:
      - 'public/*'

jobs:
  check:

    permissions:
      pull-requests: write
    
    name: Check Assets Sizes
    uses: ./.github/workflows/blank.yml
    secrets: inherit
    with:
      ignored_paths: |
        ./public/IMG_1395.JPG
      asset_paths: |
        ./public
      types: |
        js:4.33MB
        txt:500KB
        svg:2MB
        png:2KB
        jpg:2MB
        json:1MB
        css:1MB
        mp4:30MB
        ico:50KB