name: Check File Sizes

on:
  push:
    branches:
      - main

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    environment: asset_size
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      id: report
      env:
          IGNORED_PATHS: ${{ vars.IGNORED_PATHS }}
          ASSET_PATHS: ${{ vars.ASSET_PATHS }}
          js: ${{ vars.js }}
          txt: ${{ vars.txt }}
          svg: ${{ vars.svg }}
          png: ${{ vars.png }}
          jpg: ${{ vars.jpg }}
          json: ${{ vars.json }}
          css: ${{ vars.css }}
          mp4: ${{ vars.mp4 }}
          ico: ${{ vars.ico }}
      run: |
        OUTPUT=$(bash ./check.sh)
        if [[ $OUTPUT =~ "::error::" ]]; then
          echo "${OUTPUT}"
          exit 1
        elif [[ $OUTPUT =~ "Warning" ]]; then
          echo "${OUTPUT}"
        else
          echo "All assets match required size"
        fi

    - name: Post report as comment
      if: ${{ always() }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const { number } = context.issue;
          const report = "${{ steps.report.outputs.report }}";
          const octokit = github.getOctokit(github.token);
          await octokit.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: `## Asset Size Report\n\n${report}`
          });
