name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - review_requested
      - ready_for_review
    branches:
      - main

jobs:
  check-commit:

    permissions:
      pull-requests: write

    name: Check commit
    uses: ./.github/workflows/blank2.yml
    secrets: inherit