name: Check File Sizes

on:
  push:
    branches:
      - main

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    environment: asset_size
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      env:
          ASSET_PATHS: '["./public/video/wellcome1_ru.mp4", "./public/IMG_1395.JPG"]'
      run: |
        echo $ASSET_PATHS
        chmod +x check.sh
        OUTPUT=$(./check.sh ${{ vars.js }} ${{ vars.txt }} ${{ vars.svg }} ${{ vars.png }} ${{ vars.jpg }} ${{ vars.json }} ${{ vars.css }} ${{ vars.mp4 }} ${{ vars.ico }} ${{ env.ASSET_PATHS }} $IGNORED_ASSETS)
        if [[ $OUTPUT =~ "::error::" ]]; then
          echo "${OUTPUT}"
          exit 1
        elif [[ $OUTPUT =~ "Warning" ]]; then
          echo "${OUTPUT}"
        else
          echo "All assets match required size"
        fi
