name: Check File Sizes

on:
  workflow_call:
    inputs:
        ignored_paths:
          required: true
          type: string
        asset_paths:
          required: true
          type: string
        js:
          required: true
          type: string
        txt:
          required: true
          type: string
        svg:
          required: true
          type: string
        png:
          required: true
          type: string
        jpg:
          required: true
          type: string
        json:
          required: true
          type: string
        css:
          required: true
          type: string
        mp4:
          required: true
          type: string
        ico:
          required: true
          type: string

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      id: report
      env:
        ignored_paths: '["./public/video/wellcome_ru.mp4", "./public/IMG_1395.JPG"]'
        asset_paths: ${{ inputs.asset_paths }}
        js: ${{ inputs.js }}
        txt: ${{ inputs.txt }}
        svg: ${{ inputs.svg }}
        png: ${{ inputs.png }}
        jpg: ${{ inputs.jpg }}
        json: ${{ inputs.json }}
        css: ${{ inputs.css }}
        mp4: ${{ inputs.mp4 }}
        ico: ${{ inputs.ico }}
      run: |
        OUTPUT=$(bash ./check.sh)
        if [[ $OUTPUT =~ "Error" ]]; then
          echo "${OUTPUT}"
          exit 1
        elif [[ $OUTPUT =~ "Warning" ]]; then
          echo "${OUTPUT}"
        else
          echo "All assets match required size"
        fi

    - name: Post report as comment
      if: ${{ always() }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ## Asset Size Report
          ${{ steps.report.outputs.report }}
