name: Check File Sizes

on:
  workflow_call:
    inputs:
        ignored_paths:
          required: true
          type: string
        asset_paths:
          required: true
          type: string
        types:
          required: true
          type: string

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Run file size check script
      id: report
      env:
        ignored_paths: ${{ inputs.ignored_paths }}
        asset_paths: ${{ inputs.asset_paths }}
        types: ${{ inputs.types }}
      run: |
        OUTPUT=$(bash ./check.sh "$types")
        if [[ $OUTPUT =~ "Error" ]]; then
          echo "${OUTPUT}"
          echo "${OUTPUT}"
          exit 1
        elif [[ $OUTPUT =~ "Warning" ]]; then
          echo "${OUTPUT}"
          echo "${OUTPUT}"
        else
          echo "All assets match required size"
        fi

    - name: Post report as comment
      if: ${{ always() }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ./report.md
