name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - review_requested
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  check-commit:

    permissions:
      pull-requests: write

    name: Check commit
    if: github.event_name == 'pull_request' && github.event.pull_request.reviews.nodes[0].state == 'APPROVED'
    uses: ./.github/workflows/blank2.yml
    secrets: inherit