name: Another Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    permissions:
      pull-requests: write
    name: Version Calculation
    uses: ./.github/workflows/blank.yml
