name: Check File Sizes

on:
  push:
    branches:
      - main

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    environment: asset_size
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      env:
          IGNORED_PATHS: '["./public/video/wellcome_ru.mp4","./public/IMG_1395.JPG"]'
          ASSET_PATHS: "./public"
          js: ${{ vars.js }}
          txt: ${{ vars.txt }}
          svg: ${{ vars.svg }}
          png: ${{ vars.png }}
          jpg: ${{ vars.jpg }}
          json: ${{ vars.json }}
          css: ${{ vars.css }}
          mp4: ${{ vars.mp4 }}
          ico: ${{ vars.ico }}
      run: |
        OUTPUT=$(bash ./check.sh)
        if [[ $OUTPUT =~ "::error::" ]]; then
          echo "${OUTPUT}"
          exit 1
        elif [[ $OUTPUT =~ "Warning" ]]; then
          echo "${OUTPUT}"
        else
          echo "All assets match required size"
        fi
