name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
  pull_request_review:
    types:
      - submitted

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  check-commit:

    permissions:
      pull-requests: write

    name: Check commit
    if: github.event.review.state == 'approved' || github.event.action == 'opened'
    uses: ./.github/workflows/blank2.yml
    secrets: inherit