name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Use last commit name from another workflow
      uses: ./.github/workflows/get-last-commit-name.yml
      id: last-commit-name
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Display Last Commit Name
      run: |
        echo "Last commit name: ${{ steps.last-commit-name.outputs.commit-name }}"