name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:  
  check-commit:
    name: Check commit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get commit message from PR
      run: |
        commit_message=$(git log --format="%s" -n 1 $GITHUB_SHA)
        echo "::set-output name=commit_message::$commit_message"

    - name: Use the commit message
      run: |
        echo "Commit message from PR: ${{ steps.get_commit_message.outputs.commit_message }}"
