name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check:

    permissions:
      pull-requests: write
    
    name: Check Assets Sizes
    uses: ./.github/workflows/blank.yml
    with:
      ignored_paths: |
        
      asset_paths: |
        ./public
      types: |
        js:1MB
        txt:500KB
        svg:2MB
        png:154KB
        jpg:2MB
        json:1MB
        css:1MB
        mp4:30MB
        ico:50KB
