name: Check File Sizes

on:
  push:
    branches:
      - main

jobs:
  check_file_sizes:
    runs-on: ubuntu-latest
    
    environment: asset_size
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run file size check script
      run: |
        echo ${{ vars.mp4 }}
        echo ${{ vars.MP4 }}
        chmod +x check.sh
        OUTPUT=$(./check.sh ${{ vars.js }} ${{ vars.txt }} ${{ vars.svg }} ${{ vars.png }} ${{ vars.jpg }} ${{ vars.json }} ${{ vars.css }} ${{ vars.mp4 }} ${{ vars.ico }})
        if [[ $OUTPUT =~ "File" ]]; then
          echo "${OUTPUT}"
          exit 1
        fi
        echo "All assets match required size"
