name: Another Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check:
    permissions:
      pull-requests: write
    name: Version Calculation
    uses: ./.github/workflows/blank.yml
    with:
      ignored_paths: |
        - ./public/video/wellcome_ru.mp4
        - ./public/IMG_1395.JPG
      asset_paths: |
        - ./public

      types: |
        js:1MB
        txt:500KB
        svg:2MB
        png:4KB
        jpg:4MB
        json:1MB
        css:1MB
        mp4:30MB
        ico:50KB
