name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'rollback'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
      commit_sha:
        required: true
        type: string
  push:
    branches:
      - development
      - staging
    paths:
      - 'front/**'

jobs:
  check:
    
    name: Check Assets Sizes
    uses: ./.github/workflows/front2.yml
    secrets: inherit
    with:
      front_paths: ./front/front-end
      bucket_url: gs://test-front
      node_version: 20.9.0