name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
  push:
    branches:
      - development
      - staging

jobs:
  check:
    permissions: write-all
    name: Check Assets Sizes
    uses: ./.github/workflows/front2.yml
    secrets:
      GCP_FRONT: ${{ secrets[format('{0}_FRONT', 'TEST')] }}
    with:
      front_paths: front/front-end
      microservice_name: test-front
      node_version: 20.9.0
      bucket_url: ${{ format('gs://test-front-{0}', 'dev') }}
      project_id: ${{ format('majestic-{0}-420321', 'energy') }}