name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'rollback'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
      commit_sha:
        required: true
        type: string
  push:
    branches:
      - development
      - staging

jobs:
  check:
    
    name: Check Assets Sizes
    uses: ./.github/workflows/front2.yml
    if: ${{ github.event_name == 'push' && startsWith(github.event.head_commit.modified, 'front/**') }}
    secrets: inherit
    with:
      front_paths: ./front/front-end
      microservice_name: test-front
      node_version: 20.9.0