name: front

on:
  workflow_dispatch:
  pull_request:
    branches:
      - development
      - main


jobs:
  front:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20.9.0'

    - name: npm install
      run: |
        cd ./front/survey-front-end
        npm install
    
    - name: npm build
      run: |
        cd ./front/survey-front-end
        npm run build