name: Another Workflow

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        type: string
  push:
    branches:
      - development
      - staging

jobs:
  check:
    permissions: write-all
    name: Check Assets Sizes
    uses: ./.github/workflows/front2.yml
    secrets:
      GCP_FRONT: ${{ secrets[format('{0}_FRONT', 'TEST')] }}
      GCP_FRONT_SECRET: ${{ secrets.SECRET_FRONT }}
    with:
      front_paths: front/front-end
      microservice_name: test-front
      node_version: 20.9.0
      gcp_secrets_manager: 'true'
      #bucket_url: ${{ format('gs://test-front-{0}', 'dev') }}
      bucket_url: ${{ github.ref_name == 'master' && 'gs://test-front-master' || 'gs://test-front-dev' }}
      project_id: ${{ format('majestic-{0}-420321', 'energy') }}
      env_test: |
        VITE_BASE_URL=${{ github.ref_name == 'master' && 'https://test-master/' || format('https://test-{0}/', 'dev') }}
        # VITE_BASE_URL=$(
        #   if [ "${{ github.ref_name }}" == "development" ]; then 
        #     echo "${{ format('https://test-{0}/', github.ref_name) }}"
        #   else 
        #     echo "https://test-master/"
        #   fi
        # )