name: Update branches

on:
  workflow_dispatch:
    inputs:
      reset_to_branch:
        description: 'Reset to branch'     
        required: true
    # branches:
    #   - development
    #   - staging

jobs:
  update-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
        
      - name: Backup target branch
        run: |
          backup_branch="backup/${{ github.ref_name }}$(date +%Y%m%d%H%M)"
          git fetch origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          git checkout -b $backup_branch
          git push origin $backup_branch
    
      - name: Save list of branches before reset
        id: save-branches
        run: |
          git fetch origin
          comm -12 <(sort <(git branch -r --no-merged origin/${{ github.event.inputs.reset_to_branch }})) <(sort <(git branch -r --merged origin/${{ github.ref_name }})) -r > branches_reset.txt    
    
      - name: Reset target branch to master
        run: |
          git fetch origin ${{ github.event.inputs.reset_to_branch }}
          git checkout ${{ github.event.inputs.reset_to_branch }}
          git pull origin ${{ github.event.inputs.reset_to_branch }}
          git checkout ${{ github.ref_name }}
          git reset --hard origin/${{ github.event.inputs.reset_to_branch }}
          git push --force origin ${{ github.ref_name }}
          
      - name: Output lost branches
        run: cat branches_reset.txt
    #   - name: Create and merge topic branches
    #     run: |
    #       # Assuming you have a script to create and merge topic branches
    #       # Replace the command below with the actual script
    #       ./scripts/create_and_merge_topics.sh
        
    #   - name: Get list of tasks from YouTrack
    #     run: |
    #       # Assuming you have a script to fetch tasks from YouTrack
    #       # Replace the command below with the actual script
    #       ./scripts/get_tasks_from_youtrack.sh
          
    #   - name: Send report to Slack
    #     env:
    #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #     run: |
    #       # Assuming you have a script to format and send report to Slack
    #       # Replace the command below with the actual script
    #       ./scripts/send_report_to_slack.sh
