name: Update branches

on:
  workflow_dispatch:
    # branches:
    #   - development
    #   - staging

jobs:
  update-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Backup target branch
        run: |
          git fetch origin ${{ github.head_ref }}
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.event.inputs.target_branch }}
          git pull origin ${{ github.event.inputs.target_branch }}
          git checkout -b backup/${{ github.event.inputs.target_branch }}
          git push origin backup/${{ github.event.inputs.target_branch }}
          
    #   - name: Reset target branch to master
    #     run: |
    #       git checkout master
    #       git pull origin master
    #       git checkout ${{ github.event.inputs.target_branch }}
    #       git reset --hard origin/master
    #       git push --force origin ${{ github.event.inputs.target_branch }}
          
    #   - name: Create and merge topic branches
    #     run: |
    #       # Assuming you have a script to create and merge topic branches
    #       # Replace the command below with the actual script
    #       ./scripts/create_and_merge_topics.sh
        
    #   - name: Get list of tasks from YouTrack
    #     run: |
    #       # Assuming you have a script to fetch tasks from YouTrack
    #       # Replace the command below with the actual script
    #       ./scripts/get_tasks_from_youtrack.sh
          
    #   - name: Send report to Slack
    #     env:
    #       SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #     run: |
    #       # Assuming you have a script to format and send report to Slack
    #       # Replace the command below with the actual script
    #       ./scripts/send_report_to_slack.sh
