name: Test massage

on:
  workflow_dispatch:

jobs:
  reset_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setting Slack Notification
        if: ${{ always() }}
        run: |
          echo "SLACK_TITLE=Test" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=Test: \n 1. <https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics|base/getpin-3466/analytics>\n 2. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3203/Location_error_for_deleting_unpaid_location|bugfix/getpin-3203/Location_error_for_deleting_unpaid_location>\n 3. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3722/Statistic-navigation-bar-periods|bugfix/getpin-3722/Statistic-navigation-bar-periods>\n 4. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3723/Statistic-boards-and-comparison|bugfix/getpin-3723/Statistic-boards-and-comparison>\n 5. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3724/Statistic-losers-and-gainers-board|bugfix/getpin-3724/Statistic-losers-and-gainers-board>\n 6. <(https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3726/Statistic-an-overview-page|bugfix/getpin-3726/Statistic-an-overview-page>\n 7. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3727/Front-Statistic-reports|bugfix/getpin-3727/Front-Statistic-reports>\n 8. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3849/photo_add_notification_about_limit|bugfix/getpin-3849/photo_add_notification_about_limit>\n 9. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3940|bugfix/getpin-3940>\n 10. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3989/add_delegated_user_to_review_templates|bugfix/getpin-3989/add_delegated_user_to_review_templates>\n 11. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-4013/Import-location-No-modal-window-for-second-try|bugfix/getpin-4013/Import-location-No-modal-window-for-second-try>\n 12. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-4071|bugfix/getpin-4071>\n 13. <https://github.com/YARANDIN-inc/getpin/compare/development...feature/getpin-3727/Statistic-reports|feature/getpin-3727/Statistic-reports>\n 14. <https://github.com/YARANDIN-inc/getpin/compare/development...feature/getpin-4030/cookiebot_integration|feature/getpin-4030/cookiebot_integration>" >> $GITHUB_ENV
          echo "SLACK_FOOTER=$(TZ="Europe/Kiev" date +"%Y-%m-%dT%H:%M:%S")" >> $GITHUB_ENV
      
      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_TITLE: '${{ env.SLACK_TITLE }}'
          SLACK_FOOTER: 'Time: ${{ env.SLACK_FOOTER }}'
          SLACK_WEBHOOK: ${{ secrets.GETPIN_DEVOPS_SLACK_CI_WEBHOOK }}
          SLACK_ICON: https://avatars.slack-edge.com/2023-02-15/4830237365520_6ec25f9ef61c9165fda5_48.jpg
          SLACKIFY_MARKDOWN: true