name: Test massage

on:
  workflow_dispatch:

jobs:
  reset_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setting Slack Notification with Blocks
        if: ${{ always() }}
        run: |
          SLACK_BLOCKS='[
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Test*"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "Test: \n 1. <https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics|base/getpin-3466/analytics>\n 2. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3203/Location_error_for_deleting_unpaid_location|bugfix/getpin-3203/Location_error_for_deleting_unpaid_location>\n 3. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3722/Statistic-navigation-bar-periods|bugfix/getpin-3722/Statistic-navigation-bar-periods>\n 4. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3723/Statistic-boards-and-comparison|bugfix/getpin-3723/Statistic-boards-and-comparison>\n 5. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3724/Statistic-losers-and-gainers-board|bugfix/getpin-3724/Statistic-losers-and-gainers-board>\n 6. <https://github.com/YARANDIN-inc/getpin/compare/development...bugfix/getpin-3726/Statistic-an-overview-page|bugfix/getpin-3726/Statistic-an-overview-page>
              }
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "Time: $(TZ=\"Europe/Kiev\" date +\"%Y-%m-%dT%H:%M:%S\")"
                }
              ]
            }
          ]'

          echo "SLACK_BLOCKS=$SLACK_BLOCKS" >> $GITHUB_ENV

      - name: Slack Notification with Blocks
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_PAYLOAD: '{ "blocks": ${{ env.SLACK_BLOCKS }} }'
          SLACK_WEBHOOK: ${{ secrets.GETPIN_DEVOPS_SLACK_CI_WEBHOOK }}
          SLACK_ICON: https://avatars.slack-edge.com/2023-02-15/4830237365520_6ec25f9ef61c9165fda5_48.jpg