name: Test massage

on:
  workflow_dispatch:

jobs:
  reset_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setting Slack Notification
        if: ${{ always() }}
        run: |
          echo "SLACK_TITLE=Test" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=Test: \n 1. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 2. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 3. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 4. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 5. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 6. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 7. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 8. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 9. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 10. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 11. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 12. [base/getpin-3466/analytics](https://github.com/YARANDIN-inc/getpin/compare/development...base/getpin-3466/analytics)\n 13. [feature/getpin-3727/Statistic-reports](https://github.com/YARANDIN-inc/getpin/compare/development...feature/getpin-3727/Statistic-reports)\n 14. [feature/getpin-4030/cookiebot_integration](https://github.com/YARANDIN-inc/getpin/compare/development...feature/getpin-4030/cookiebot_integration)" >> $GITHUB_ENV
          echo "SLACK_FOOTER=$(TZ="Europe/Kiev" date +"%Y-%m-%dT%H:%M:%S")" >> $GITHUB_ENV
      
      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ${{ env.SLACK_MESSAGE }}
          SLACK_TITLE: '${{ env.SLACK_TITLE }}'
          SLACK_FOOTER: 'Time: ${{ env.SLACK_FOOTER }}'
          SLACK_WEBHOOK: ${{ secrets.GETPIN_DEVOPS_SLACK_CI_WEBHOOK }}
          SLACK_ICON: https://avatars.slack-edge.com/2023-02-15/4830237365520_6ec25f9ef61c9165fda5_48.jpg
          SLACKIFY_MARKDOWN: true